# Generated by Django 2.1.1 on 2019-01-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='project',
            new_name='header',
        ),
    ]
