# Generated by Django 2.1.1 on 2018-09-09 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){4,}$]', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cragheart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){4,}$]', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('item_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mindthief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){4,}$]', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paladin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){4,}$]', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prosperity', models.IntegerField()),
                ('reputation', models.CharField(max_length=50)),
                ('members', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scoundrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){4,}$]', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tinkerer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){4,}$]', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
