# Generated by Django 2.1.1 on 2018-09-09 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brute',
            name='items',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$]', 'Enter the 3 digit item number')]),
        ),
        migrations.AlterField(
            model_name='cragheart',
            name='items',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$]', 'Enter the 3 digit item number')]),
        ),
        migrations.AlterField(
            model_name='mindthief',
            name='items',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$]', 'Enter the 3 digit item number')]),
        ),
        migrations.AlterField(
            model_name='paladin',
            name='items',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$]', 'Enter the 3 digit item number')]),
        ),
        migrations.AlterField(
            model_name='scoundrel',
            name='items',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$]', 'Enter the 3 digit item number')]),
        ),
        migrations.AlterField(
            model_name='tinkerer',
            name='items',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$]', 'Enter the 3 digit item number')]),
        ),
    ]
