# Generated by Django 2.1.1 on 2018-09-13 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_party_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('level', models.IntegerField()),
                ('items', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9]{3},?){1,}$', 'Enter the 3 digit item number')])),
                ('perks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='brute',
            name='party',
        ),
        migrations.RemoveField(
            model_name='cragheart',
            name='party',
        ),
        migrations.RemoveField(
            model_name='mindthief',
            name='party',
        ),
        migrations.RemoveField(
            model_name='paladin',
            name='party',
        ),
        migrations.RemoveField(
            model_name='scoundrel',
            name='party',
        ),
        migrations.RemoveField(
            model_name='tinkerer',
            name='party',
        ),
        migrations.DeleteModel(
            name='Brute',
        ),
        migrations.DeleteModel(
            name='Cragheart',
        ),
        migrations.DeleteModel(
            name='Mindthief',
        ),
        migrations.DeleteModel(
            name='Paladin',
        ),
        migrations.DeleteModel(
            name='Scoundrel',
        ),
        migrations.DeleteModel(
            name='Tinkerer',
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Character_class'),
        ),
        migrations.AddField(
            model_name='character',
            name='party',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Party'),
        ),
    ]
