# Generated by Django 2.1.1 on 2018-09-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180913_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Character_class'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='items',
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
